default_platform(:ios)

platform :ios do
  lane :dev_release do
    build_app(
      scheme: "Agios Beta",
      export_method: "app-store",
      export_options: { 
        provisioningProfiles: {
          "com.danielkame.AgiosBeta" => "Agios Beta Distribution",
          "com.danielkame.AgiosBeta.AgiosWidgetBeta" => "Agios Beta Widget Distribution"
        }
      }
    )

    upload_to_testflight(
      api_key: fetch_app_store_api_key,
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end
end

def fetch_app_store_api_key
  app_store_connect_api_key(
    key_id: ENV["APP_STORE_API_KEY_ID"],
    issuer_id: ENV["APP_STORE_ISSUER_ID"],
    key_content: ENV["APP_STORE_API_KEY"],
    in_house: false
  )
end