name: TestFlight Prod Release

on:
  workflow_dispatch:

jobs:
  release:
    concurrency:
      group: testflight-prod-release
      cancel-in-progress: true
      
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Apple certificate and provisioning profiles
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64_PROD }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        AGIOS_PROVISIONING_PROFILE: ${{ secrets.AGIOS_PROVISIONING_PROFILE_PROD }}
        AGIOS_WIDGET_PROVISIONING_PROFILE: ${{ secrets.AGIOS_WIDGET_PROVISIONING_PROFILE_PROD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        CERT_PATH=$RUNNER_TEMP/cert.p12
        PROFILE_APP=$RUNNER_TEMP/agios_app.mobileprovision
        PROFILE_WIDGET=$RUNNER_TEMP/agios_widget.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/signing.keychain-db

        echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o "$CERT_PATH"
        echo "$AGIOS_PROVISIONING_PROFILE" | base64 --decode -o "$PROFILE_APP"
        echo "$AGIOS_WIDGET_PROVISIONING_PROFILE" | base64 --decode -o "$PROFILE_WIDGET"

        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security import "$CERT_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
        security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security list-keychains -d user -s "$KEYCHAIN_PATH"

        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp "$PROFILE_APP" ~/Library/MobileDevice/Provisioning\ Profiles/
        cp "$PROFILE_WIDGET" ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Set up bundler
      run: |
        gem install bundler
        bundle install

    - name: Decode App Store Connect API Key
      run: |
        echo "${{ secrets.APP_STORE_API_KEY }}" > AuthKey.p8

    - name: Build and upload to TestFlight (Production)
      env:
        APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
        APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
        APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
      run: |
        bundle exec fastlane prod_release
